<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.18.0.0</Version>
    <PackageProjectUrl>https://github.com/Senither/AutoWeeklyCap</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ECommons" Version="3.2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="resources\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>resources\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Secrets.example.cs"/>
  </ItemGroup>

  <Target Name="GenerateSecretsIfMissing" BeforeTargets="CoreCompile">
    <PropertyGroup>
      <_SecretsExisted Condition="Exists('$(MSBuildThisFileDirectory)Secrets.cs')">true</_SecretsExisted>
      <_SecretsExisted Condition="!Exists('$(MSBuildThisFileDirectory)Secrets.cs')">false</_SecretsExisted>
    </PropertyGroup>
    <Copy SourceFiles="$(MSBuildThisFileDirectory)Secrets.example.cs"
          DestinationFiles="$(MSBuildThisFileDirectory)Secrets.cs"
          Condition="!$(_SecretsExisted)"/>
    <ItemGroup>
      <Compile Include="$(MSBuildThisFileDirectory)Secrets.cs" Condition="!$(_SecretsExisted)"/>
    </ItemGroup>
  </Target>
</Project>
